base:
  mass: 2.5               # Base mass in Kg
  x_size: 0.300           # Dimension in x axis
  y_size: 0.200           # Dimension in y axis
  z_size: 0.050          # Dimension in z axis
  mesh: ''  # Name of the mesh files. Leave it empty ('') to have a white base.